"""Wrapper around interacting with the control plane, which may be multiple brokers."""

import itertools
import re

from ..config import ControlPlaneConfig
from ..exceptions import IntersectSetupError
from ..logger import logger
from .brokers.broker_client import BrokerClient
from .definitions import MessageCallback
from .topic_handler import TopicHandler

_CHANNEL_REGEX = re.compile(r'^[a-zA-Z0-9*/-]+[a-zA-Z0-9*#/-]$')
"""Allow for these patterns:

- alphanumeric characters
- hyphens
- `/` (topic separator; note that this is '.' on the broker)
- `*` (wildcard for exactly one word)
- `#` (wildcard for any number of words, but can ONLY appear at the end of the topic string, see section 4.7.1.2 at https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718107)
"""


def _create_control_provider(
    config: ControlPlaneConfig,
    control_plane_manager: 'ControlPlaneManager',
) -> BrokerClient:
    if config.protocol == 'amqp0.9.1':
        from .brokers.amqp_client import (  # noqa: PLC0415 (lazy load all AMQP modules)
            AMQPClient,
        )

        return AMQPClient(
            host=config.host,
            port=config.port or 5672,
            username=config.username,
            password=config.password,
            control_plane_manager=control_plane_manager,
            is_root=config.is_root,
        )

    # MQTT
    from .brokers.mqtt_client import MQTTClient  # noqa: PLC0415 (lazy load MQTT modules)

    return MQTTClient(
        host=config.host,
        port=config.port or 1883,
        username=config.username,
        password=config.password,
        control_plane_manager=control_plane_manager,
    )


class ControlPlaneManager:
    """The ControlPlaneManager class allows for working with multiple brokers from a single function call."""

    def __init__(
        self,
        control_configs: list[ControlPlaneConfig],
    ) -> None:
        """Basic constructor.

        Some interaction with message brokers can change based on whether or not a Service or a Client is calling it.

        queue_name_generator should be a hardcoded value for Core Services, the SDK should provide its own function to generate queue names.
        """
        self._control_providers = [
            _create_control_provider(config, self) for config in control_configs
        ]

        # flag which indicates if we SHOULD be connected.
        self._ready = False
        # topics_to_handlers are managed here and transcend connections/disconnections to the broker
        self._topics_to_handlers: dict[str, TopicHandler] = {}
        self._wildcards: dict[str, TopicHandler] = {}

    def add_subscription_channel(
        self, channel: str, callbacks: set[MessageCallback], persist: bool, queue_name: str
    ) -> None:
        """Start listening for messages on a channel on all configured brokers.

        The provided channel value should be PROTOCOL AGNOSTIC. Use the following symbols when constructing a topic:
        - `/` - topic separator
        - `*` - exactly one word
        - `#` - any number of words (however, this can only be used as the LAST character)

        Protocol implementations are responsible for converting the string to a valid channel.

        This function should usually only be called before you've connected,
        but it's okay to call it after connecting. (Mostly used for Clients.)

        Params:
          channel: string of the channel which we should start listening to, remember to follow the above protocol agnostic convention
          callbacks: functions to call on subscribing to a message
          persist: if True, expect the associated message queue to live long; if False, it will only live the duration of the application.
            Any queue associated with a Service should always set this to True. Clients will need to subscribe to their own, temporary queues, and should set this to False.
          queue_name: the name of the queue to subscribe to. This is generally hardcoded for Core Services, but autogenerated for SDK Services and Clients.
        """
        # this currently follows the MQTT/AMQP convention for wildcards
        # '*' = exactly one word (AMQP), '+' = exactly one word (MQTT), '#' = any number of words (AMQP and MQTT)
        if not _CHANNEL_REGEX.match(channel):
            msg = f'Channel {channel} is not valid, it must be alphanumeric and can only contain the following special characters: * # / -'
            raise IntersectSetupError(msg)
        is_wildcard = '*' in channel or channel.endswith('#')
        dict_to_change = self._wildcards if is_wildcard else self._topics_to_handlers

        topic_handler = dict_to_change.get(channel)
        if topic_handler is None:
            topic_handler = TopicHandler(persist, queue_name, channel if is_wildcard else None)
            topic_handler.callbacks |= callbacks
            dict_to_change[channel] = topic_handler
        else:
            topic_handler.callbacks |= callbacks
            topic_handler.topic_persist = persist
            topic_handler.queue_name = queue_name
        if self.is_connected():
            for provider in self._control_providers:
                provider.subscribe(channel, persist, queue_name)

    def remove_subscription_channel(self, channel: str) -> bool:
        """Stop subscribing to a channel on all configured brokers.

        Params:
          channel: string of the channel which should no longer be listened to
        Returns: True if channel is no longer being listened to, False if the channel wasn't being listened to in the first place
        """
        try:
            del self._topics_to_handlers[channel]
        except KeyError:
            try:
                del self._wildcards[channel]
            except KeyError:
                return False
        if self.is_connected():
            for provider in self._control_providers:
                provider.unsubscribe(channel)
        return True

    def get_non_wildcard_subscription_channels(self) -> dict[str, TopicHandler]:
        """Get primary subscription channels.

        These channels cannot be wildcards, and incoming topics must match the channel topics exactly.

        This function is safe to call from the broker clients, as it does not mutate state.

        Returns:
          the dictionary of topics to topic information
        """
        return self._topics_to_handlers

    def get_wildcard_topic_and_topic_handler(self, topic: str) -> tuple[str, TopicHandler] | None:
        """Get the wildcard topic handler for a given topic, if it exists.

        This is an inefficient lookup, so should only be used if we fail to find a non-wildcard match for an incoming topic. Note that this function gets accessed as a callback from the direct broker implementations.

        This function is safe to call from the broker clients, as it does not mutate state.

        Params:
          topic: the topic for an incoming message (this will not have any wildcards in it)

        Returns:
          if a match found: the wildcard string configured application-side to match the topic parameter, and the topic handler associated with the topic
          if no match found: None
        """
        for wildcard, topic_handler in self._wildcards.items():
            if topic_handler.does_topic_match(topic):
                return wildcard, topic_handler
        return None

    def get_all_subscription_channels(self) -> itertools.chain[tuple[str, TopicHandler]]:
        """Get all subscription channels, including wildcard channels.

        This function is safe to call from the broker clients, as it does not mutate state.

        Returns:
            an iterator which yields tuples of (channel, topic handler) for all channels, including wildcards. Note that wildcard channels will be returned in no particular order, and may be interspersed with non-wildcard channels.
        """
        return itertools.chain(self._topics_to_handlers.items(), self._wildcards.items())

    def connect(self) -> None:
        """Connect to all configured brokers.

        Each broker client should utilize their respective on_connect callback to
        subscribe to all channels tracked in the ControlPlaneManager.
        """
        for provider in self._control_providers:
            provider.connect()
        self._ready = True

    def disconnect(self) -> None:
        """Disconnect from all configured brokers."""
        self._ready = False
        for provider in self._control_providers:
            provider.disconnect()

    def publish_message(
        self,
        channel: str,
        payload: bytes,
        content_type: str,
        headers: dict[str, str],
        persist: bool,
    ) -> None:
        """Publish message on channel for all brokers."""
        if self.is_connected():
            for provider in self._control_providers:
                provider.publish(channel, payload, content_type, headers, persist)
        else:
            # TODO may want more robust error handling here
            logger.error('Cannot send message, providers are not connected')

    def is_connected(self) -> bool:
        """Check that we are connected to ALL configured brokers.

        Returns:
          - True if we are currently connected to all brokers we've configured, False if not
        """
        return self._ready and all(
            control_provider.is_connected() for control_provider in self._control_providers
        )

    def considered_unrecoverable(self) -> bool:
        """Check if any broker is considered to be in an unrecoverable state.

        Returns:
          - True if we can't recover, false otherwise
        """
        return any(
            control_provider.considered_unrecoverable()
            for control_provider in self._control_providers
        )
